# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='attachment',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='message',
            name='read',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='mtype',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='recv_uid',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='message',
            name='send_uid',
            field=models.IntegerField(default=0),
        ),
    ]
