# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-31 11:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0002_auto_20170527_0819'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='group_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='message',
            name='read_time',
            field=models.DateTimeField(default='1970-01-01 00:00:00.000000'),
        ),
        migrations.AddField(
            model_name='message',
            name='send_time',
            field=models.DateTimeField(default='1970-01-01 00:00:00.000000'),
        ),
        migrations.AddField(
            model_name='message',
            name='title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='message',
            name='recv_uid',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(default=''),
        ),
    ]
