# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0003_auto_20170531_1139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='group_id',
            new_name='group',
        ),
    ]
