# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 08:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0004_auto_20170626_0735'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='read_time',
        ),
    ]
