# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-27 01:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0005_remove_message_read_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='meta',
            field=models.TextField(default='{}'),
        ),
    ]
