# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0006_message_meta'),
    ]

    operations = [
        migrations.CreateModel(
            name='Handbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htype', models.CharField(default='.', max_length=2)),
                ('review_id', models.IntegerField(default=0)),
                ('submit_id', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('content', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ntype', models.CharField(default='.', max_length=2)),
                ('display_id', models.IntegerField(default=0)),
                ('year', models.IntegerField(default=0)),
                ('title', models.TextField(default='')),
                ('text', models.TextField(default='')),
            ],
        ),
    ]
