# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-20 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0007_handbook_news'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='ntype',
            new_name='display_type',
        ),
    ]
