# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0008_auto_20170720_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='handbook',
            name='htype',
            field=models.CharField(default='.', max_length=1),
        ),
        migrations.AlterField(
            model_name='news',
            name='display_type',
            field=models.CharField(default='.', max_length=1),
        ),
    ]
