# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-04 07:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0010_jiatuanmaterial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jiatuanmaterial',
            old_name='display_type',
            new_name='htype',
        ),
        migrations.RenameField(
            model_name='jiatuanmaterial',
            old_name='display_id',
            new_name='submit_id',
        ),
        migrations.AddField(
            model_name='jiatuanmaterial',
            name='review_id',
            field=models.IntegerField(default=0),
        ),
    ]
