# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0011_auto_20170804_0736'),
    ]

    operations = [
        migrations.AddField(
            model_name='handbook',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
