# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0012_handbook_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='jiatuanmaterial',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='jiatuanmaterial',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
    ]
