# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0013_auto_20170904_0749'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jiatuanmaterial',
            name='htype',
        ),
        migrations.RemoveField(
            model_name='jiatuanmaterial',
            name='review_id',
        ),
    ]
