# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 06:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0014_auto_20170904_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='year',
        ),
        migrations.AddField(
            model_name='news',
            name='post_time',
            field=models.DateTimeField(default='1970-01-01 00:00:00.000000'),
        ),
    ]
