# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0015_auto_20171122_0602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_type', models.CharField(default='.', max_length=1)),
                ('display_id', models.IntegerField(default=0)),
                ('title', models.TextField(default='')),
                ('text', models.TextField(default='')),
                ('img_path', models.TextField(default='')),
            ],
        ),
    ]
