# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 07:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Message', '0016_slide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='slide',
            name='text',
        ),
    ]
