# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Handbook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('htype', models.CharField(default='n', max_length=2)),
                ('review_id', models.IntegerField(default=0)),
                ('submit_id', models.IntegerField(default=0)),
                ('content', models.TextField(default='')),
            ],
        ),
    ]
