# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 02:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUser', '0002_auto_20170523_2242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='suser',
            name='authority',
        ),
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='suser',
            name='admin_branch',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='suser',
            name='admin_department',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='suser',
            name='admin_school',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='suser',
            name='admin_super',
            field=models.BooleanField(default=False),
        ),
    ]
