# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 03:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUser', '0003_auto_20170527_0251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='suser',
            field=models.TextField(default='[]'),
        ),
        migrations.AlterField(
            model_name='department',
            name='branch',
            field=models.TextField(default='[]'),
        ),
    ]
