# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 04:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SUser', '0005_auto_20170527_0424'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='branch',
        ),
    ]
