# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-26 08:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUser', '0008_auto_20170626_0637'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='member',
            field=models.TextField(default='[]'),
        ),
    ]
