# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-03 02:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SUser', '0009_branch_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide', models.TextField(default='[]')),
            ],
        ),
        migrations.AddField(
            model_name='branch',
            name='slide',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='department',
            name='slide',
            field=models.TextField(default='[]'),
        ),
    ]
