# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-11-22 07:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SUser', '0010_auto_20170803_0227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
        migrations.RemoveField(
            model_name='branch',
            name='slide',
        ),
        migrations.RemoveField(
            model_name='department',
            name='slide',
        ),
    ]
